# Generated by Django 3.2.6 on 2021-10-02 01:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.IntegerField(choices=[(30, '30 min'), (40, '40 min'), (50, '50 min'), (60, '60 min'), (90, '90 min'), (120, '120 min')], default=60)),
                ('num_days', models.IntegerField(default=7)),
                ('holidays', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=list, size=None)),
                ('monday', models.JSONField(default=dict)),
                ('tuesday', models.JSONField(default=dict)),
                ('wednesday', models.JSONField(default=dict)),
                ('thursday', models.JSONField(default=dict)),
                ('friday', models.JSONField(default=dict)),
                ('saturday', models.JSONField(default=dict)),
                ('sunday', models.JSONField(default=dict)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='card.card')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='card.card')),
            ],
        ),
    ]
