# Generated by Django 3.2.6 on 2021-10-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
