# Generated by Django 3.2.6 on 2021-10-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_appointment_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('email', 'date', 'slot'), name='unique_booking'),
        ),
    ]
