# Generated by Django 3.2.6 on 2021-10-07 00:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_appointment_unique_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.CharField(max_length=11, verbose_name='slot'),
        ),
        migrations.AlterField(
            model_name='availableslots',
            name='friday',
            field=models.JSONField(default=dict, verbose_name='friday'),
        ),
        migrations.AlterField(
            model_name='availableslots',
            name='holidays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=list, size=None, verbose_name='holidays'),
        ),
        migrations.AlterField(
            model_name='availableslots',
            name='monday',
            field=models.JSONField(default=dict, verbose_name='monday'),
        ),
        migrations.AlterField(
            model_name='availableslots',
            name='num_days',
            field=models.IntegerField(default=7, verbose_name='number of days'),
        ),
        migrations.AlterField(
            model_name='availableslots',
            name='range',
            field=models.IntegerField(choices=[(30, '30 min'), (40, '40 min'), (50, '50 min'), (60, '60 min'), (90, '90 min'), (120, '120 min')], default=60, verbose_name='range'),
        ),
        migrations.AlterField(
            model_name='availableslots',
            name='saturday',
            field=models.JSONField(default=dict, verbose_name='saturday'),
        ),
        migrations.AlterField(
            model_name='availableslots',
            name='sunday',
            field=models.JSONField(default=dict, verbose_name='sunday'),
        ),
        migrations.AlterField(
            model_name='availableslots',
            name='thursday',
            field=models.JSONField(default=dict, verbose_name='thursday'),
        ),
        migrations.AlterField(
            model_name='availableslots',
            name='tuesday',
            field=models.JSONField(default=dict, verbose_name='tuesday'),
        ),
        migrations.AlterField(
            model_name='availableslots',
            name='wednesday',
            field=models.JSONField(default=dict, verbose_name='wednesday'),
        ),
    ]
