# Generated by Django 3.2.8 on 2021-10-13 23:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20211007_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableslots',
            name='holidays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=list, help_text='Holidays or not working days', size=None, verbose_name='holidays'),
        ),
        migrations.AlterField(
            model_name='availableslots',
            name='num_days',
            field=models.IntegerField(default=7, help_text='Max number of days in th future allowed', verbose_name='number of days'),
        ),
        migrations.AlterField(
            model_name='availableslots',
            name='range',
            field=models.IntegerField(choices=[(30, '30 min'), (40, '40 min'), (50, '50 min'), (60, '60 min'), (90, '90 min'), (120, '120 min')], default=60, help_text='Slots range', verbose_name='range'),
        ),
    ]
