# Generated by Django 3.2.8 on 2021-11-10 22:11

import authentication.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=authentication.utils.make_file_path)),
                ('background', models.ImageField(blank=True, help_text='Suggested size: 1920x1080 px', null=True, upload_to=authentication.utils.make_file_path)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone')),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=authentication.utils.make_file_path, verbose_name='image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='card.card')),
            ],
        ),
    ]
