# Generated by Django 3.2.8 on 2021-11-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
