# Generated by Django 3.2.6 on 2021-10-02 18:27

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.utils.make_file_path),
        ),
    ]
