# Generated by Django 3.2.6 on 2021-10-03 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_service_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
