# Generated by Django 3.2.6 on 2021-10-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='contact_messages_count',
            field=models.IntegerField(default=0),
        ),
    ]
