# Generated by Django 3.2.8 on 2021-11-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_card_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='google_map',
            field=models.TextField(blank=True, null=True),
        ),
    ]
