# Generated by Django 3.2.6 on 2021-10-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_card_contact_messages_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
