# Generated by Django 3.2.8 on 2021-11-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_card_google_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='email',
            field=models.EmailField(default='rcotillo@cotillo.tech', max_length=254),
            preserve_default=False,
        ),
    ]
