# Generated by Django 3.2.6 on 2021-10-05 00:10

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_auto_20211004_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='icon',
            field=models.ImageField(blank=True, help_text='Icono que se mostrara en el celular 512x512 pixeles', null=True, upload_to=authentication.utils.make_file_path),
        ),
    ]
