# Generated by Django 3.2.8 on 2021-12-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_registrationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='card',
        ),
        migrations.AddField(
            model_name='product',
            name='card',
            field=models.ManyToManyField(related_name='products', to='card.Card'),
        ),
    ]
