# Generated by Django 3.2.6 on 2021-10-05 00:12

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_card_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='icon_small',
            field=models.ImageField(blank=True, help_text='Icono que se mostrara en el celular 192x192 pixeles', null=True, upload_to=authentication.utils.make_file_path),
        ),
    ]
