# Generated by Django 3.2.6 on 2021-10-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_card_icon_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
