# Generated by Django 3.2.8 on 2021-12-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_auto_20211205_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='card',
        ),
        migrations.AddField(
            model_name='card',
            name='products',
            field=models.ManyToManyField(related_name='card', to='card.Product'),
        ),
    ]
