# Generated by Django 3.2.6 on 2021-10-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(default='#8BB53C', max_length=15),
        ),
    ]
