# Generated by Django 3.2.6 on 2021-10-05 02:03

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_alter_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background',
            field=models.ImageField(blank=True, help_text='Tamaño sugerido: 1920x1080 pixeles', null=True, upload_to=authentication.utils.make_file_path),
        ),
    ]
