# Generated by Django 3.2.6 on 2021-10-07 00:33

import authentication.utils
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_alter_card_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['user__first_name', 'user__last_name']),
        ),
        migrations.AlterField(
            model_name='card',
            name='background',
            field=models.ImageField(blank=True, help_text='Suggested size: 1920x1080 px', null=True, upload_to=authentication.utils.make_file_path),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(default='#8BB53C', help_text='Determine the primary color of your Identicard', max_length=15),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='card',
            name='external_catalog_link',
            field=models.URLField(blank=True, null=True, verbose_name='external catalog link'),
        ),
        migrations.AlterField(
            model_name='card',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.utils.make_file_path, verbose_name='featured image'),
        ),
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.ImageField(blank=True, help_text='This icon will show as app icon. 512x512 px', null=True, upload_to=authentication.utils.make_file_path, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='card',
            name='icon_small',
            field=models.ImageField(blank=True, help_text='This icon will show as app icon. 192x192 px', null=True, upload_to=authentication.utils.make_file_path, verbose_name='icon small'),
        ),
        migrations.AlterField(
            model_name='card',
            name='qrcode',
            field=models.FileField(blank=True, null=True, upload_to=authentication.utils.make_file_path, verbose_name='qr code'),
        ),
        migrations.AlterField(
            model_name='card',
            name='video',
            field=models.URLField(blank=True, help_text='This fields only accepts Youtube links', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.utils.make_file_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=300, verbose_name='name'),
        ),
    ]
