# Generated by Django 3.2.6 on 2021-10-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_auto_20211007_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='featured_text',
            field=models.TextField(blank=True, null=True, verbose_name='featured text'),
        ),
    ]
