# Generated by Django 3.2.8 on 2021-10-12 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_card_featured_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='template',
        ),
    ]
