# Generated by Django 3.2.8 on 2021-10-13 23:51

import authentication.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_remove_card_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=authentication.utils.make_file_path)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing', to='card.card')),
            ],
        ),
    ]
