# Generated by Django 3.2.8 on 2021-10-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_landing_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='message',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
