# Generated by Django 3.2.8 on 2021-10-14 04:04

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0016_alter_landing_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='soundcloud',
            field=models.TextField(blank=True, help_text='Paste embeded Soundcloud html', null=True),
        ),
        migrations.AlterField(
            model_name='landing',
            name='image',
            field=models.ImageField(help_text='Suggested proportion: 9:16', upload_to=authentication.utils.make_file_path),
        ),
        migrations.AlterField(
            model_name='landing',
            name='message',
            field=models.CharField(blank=True, help_text='Maximun characters: 150', max_length=150, null=True),
        ),
    ]
