# Generated by Django 3.2.8 on 2021-10-14 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_permission_name'),
        ('card', '0017_auto_20211014_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='authentication.permission'),
        ),
    ]
