# Generated by Django 3.2.8 on 2021-10-14 22:46

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0018_card_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='image',
            field=models.ImageField(blank=True, help_text='Suggested proportion: 9:16', null=True, upload_to=authentication.utils.make_file_path),
        ),
    ]
