# Generated by Django 3.2.8 on 2021-10-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0019_alter_landing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='soundcloud',
        ),
        migrations.AddField(
            model_name='card',
            name='podcast',
            field=models.URLField(blank=True, help_text='Paste spotify link to playlist', null=True),
        ),
    ]
