# Generated by Django 3.2.8 on 2021-10-21 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0020_auto_20211020_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='notification_key',
        ),
        migrations.RemoveField(
            model_name='card',
            name='notification_key_name',
        ),
    ]
