# Generated by Django 3.2.6 on 2021-10-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
