# Generated by Django 3.2.8 on 2021-10-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Professional')], default=1)),
            ],
        ),
    ]
