# Generated by Django 3.2.8 on 2021-10-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='allow_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='allow_landing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='allow_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='allow_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='level',
            field=models.IntegerField(choices=[(1, 'Standard'), (2, 'Advanced'), (3, 'Professional')], default=1),
        ),
    ]
