# Generated by Django 3.2.8 on 2021-10-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20211014_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(default='Standard', max_length=255),
            preserve_default=False,
        ),
    ]
