# Generated by Django 3.2.8 on 2021-10-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_permission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='allow_podcast',
            field=models.BooleanField(default=False),
        ),
    ]
